
const getters = {
  language: state => state.app.language,
  token: state => state.app.token,
  dishNums: state => state.app.dishNums,
  dinersNum: state => state.app.dinersNum,
  totalNum: state => state.app.totalNum,
  curentStore: state => state.app.curentStore,
  take_out: state => state.app.take_out,
  cartDishNums: state => state.app.cartDishNums,
  dishListType: state => state.app.dishListType,
  showShareCode: state => state.app.showShareCode,
  showShopCart: state => state.app.showShopCart,
  order_mode: state => state.app.order_mode,
  scan_language: state => state.app.scan_language,
  fixToken: state => state.app.fixToken,
  order_source: state => state.app.order_source,
  order_id: state => state.app.order_id,
  tb_id: state => state.app.tb_id,
  qrcode: state => state.app.qrcode,
  ipayQrcode: state => state.app.ipayQrcode,
  cartOrder_id: state => state.app.cartOrder_id,
  serverUrl:state => state.app.serverUrl,
  storeTakeOut:state => state.app.storeTakeOut,
  isYuYue:state => state.app.isYuYue,
  openTimeJson:state => state.app.openTimeJson,
  yuYueTime:state => state.app.yuYueTime,
  deliveryInfo:state => state.app.deliveryInfo,
}
export default getters